mysite/accounts/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views


app_name = 'accounts' #for namespacing of urls

urlpatterns = [path('', RedirectView.as_view(url = '/accounts/login/'), name = 'go-to-login'),
               path('signup/', views.register, name = 'Register'),
               path('login/', views.userLogin, name = 'login'),
               path('logout/', views.logout_view, name = 'logout')
               ]

mysite/drview/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView


app_name = 'drview' #for namespacing of urls

urlpatterns = [path('', RedirectView.as_view(url = '/dr-portal/home'), name = 'go-to-home'),
               path('home/', views.home, name = 'homepage'),
               path('calendar/', views.schedule, name = 'calendar'),
               path('patient-autocomplete/', views.patientAutoComplete.as_view(), name = 'patient-autocomplete')
               ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testsite/', include('testsite.urls')),
    path('', include('testsite.urls')),
    path('accounts/', include('accounts.urls')),
    path('dr-portal/', include('drview.urls')),
    path('patient-portal/', include('patientview.urls')),
]

mysite/testsite/urls.py
from django.urls import path, include
from . import views

app_name = 'testsite'

urlpatterns = [path('', views.index, name = 'test'),
               path('testlink/', views.link, name = 'link'),
               ]

mysite/drview/models.py
from django.db import models
from django.contrib.auth.models import User
from patientview.models import Patient
from django.utils.translation import gettext as _

class Specialty(models.Model):

    specialty = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.specialty

class Doctor(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(max_length=256)
    specialties = models.ManyToManyField(Specialty,  blank=True, related_name='specialty_of')
    treats = models.ManyToManyField(Patient, blank=True, related_name='treated_by')
    appts = models.ManyToManyField(Patient, through='Appointments')

    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return ('{} {}'.format(self.first_name, self.last_name))

class Appointments(models.Model):
    #Choices for dropdown and repetition.
    NONE = ''
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'
    REPETITION_CHOICES = [
        (NONE, _('Repeat:')),
        (DAILY, _('Daily')),
        (WEEKLY, _('Weekly')),
        (MONTHLY, _('Monthly')),
    ]
    MONDAY = 'MO'
    TUESDAY = 'TU'
    WEDNESDAY = 'WE'
    THURSDAY = 'TH'
    FRIDAY = 'FR'
    WEEKDAY_CHOICES = [
        (MONDAY, _('Mon')),
        (TUESDAY, _('Tues')),
        (WEDNESDAY, _('Wed')),
        (THURSDAY, _('Thurs')),
        (FRIDAY, _('Fri')),
    ]

    #Model Fields
    starts_at = models.DateTimeField()
    ends_at = models.DateTimeField()
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    appt_location = models.CharField(max_length=100, null=True)
    appt_doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    appt_patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    reason = models.TextField(max_length=256, null=True)
    rrule = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return "{0} - {1}: {2} Appointment with {3}".format(self.starts_at, self.ends_at, self.appt_doctor,  self.appt_patient)

mysite/drview/forms.py
from django import forms
from .models import Appointments
from dal import autocomplete
from datetime import datetime
from django.utils.translation import gettext as _

class addAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(addAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['appt_patient'].queryset = self.user.treats.all()

    date = forms.DateField(label='Date',
                           widget=forms.DateInput(attrs={'class': 'datepicker form-control', 'placeholder': 'Date'}))
    starts_at = forms.TimeField(label='Start Time:', widget=forms.DateInput(
        attrs={'class': 'timepicker form-control', 'placeholder': 'Start Time'}))
    ends_at = forms.TimeField(label='End Time:', widget=forms.DateInput(
        attrs={'class': 'timepicker form-control', 'placeholder': 'End Time'}))
    appt_location = forms.CharField(label='Location', max_length=100,
                                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Location'}),
                                    required=False)
    reason = forms.CharField(label='Reason for Visit:', max_length=500,
                             widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Reason for Visit'}),
                             required=False)

    byweekday = forms.MultipleChoiceField(choices=Appointments.WEEKDAY_CHOICES,
                                          widget = forms.CheckboxSelectMultiple(attrs={'name':'weekday'}),
                                          required=False)

    frequency = forms.ChoiceField(widget=forms.Select({'class': 'form-control', 'data-target': 'weekdayCollapse'}),
                              choices=Appointments.REPETITION_CHOICES,
                              required=False)

    class Meta:
        model = Appointments
        fields = ('appt_patient', 'appt_location', 'reason',)
        widgets = {
            'appt_patient': autocomplete.ModelSelect2(url='drview:patient-autocomplete',
                                                      attrs={'class':'form-control',
                                                             'theme':'bootstrap',
                                                             'data-placeholder': 'Patient Name'})
        }

    # def is_valid(self):
    #     valid = super(addAppointmentForm, self).is_valid()
    #     self.cd = self.cleaned_data
    #     start_time = self.cd.get('starts_at')
    #     end_time = self.cd.get('ends_at')
    #
    #     if not valid:
    #         raise forms.ValidationError(_('Invalid form entry.'), code='invalid')
    #     elif start_time > end_time:
    #         raise forms.ValidationError(_('Start time must be before end time.'), code='Bad date order')
    #     else:
    #         return True

    def clean(self):
        self.cd = super(addAppointmentForm, self).clean()
        start_time = self.cd.get('starts_at')
        end_time = self.cd.get('ends_at')
        if start_time > end_time:
            raise forms.ValidationError(_('Start time must be before end time.'), code='Bad date order')
        return self.cd



    def save(self):

        start_datetime = datetime.combine(self.cd['date'], self.cd['starts_at'])
        end_datetime = datetime.combine(self.cd['date'], self.cd['ends_at'])
        weekdays = self.cd['byweekday']
        if self.cd['frequency']:
            frequency = r'DTSTART:{0};\nRRULE:FREQ={1};BYDAY={2}'.format(start_datetime.strftime('%Y%m%dT%H%M%S'), self.cd['frequency'], ','.join(map(str, weekdays)))
        else:
            frequency = ''

        self.instance.starts_at = start_datetime
        self.instance.ends_at = end_datetime
        self.instance.rrule = frequency
        self.instance.appt_doctor = self.user

        super(addAppointmentForm, self).save(commit=True)

mysite/drview/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .decorators import allowed_roles_redirect
from .static.drview.pyscripts.script_snippets import makePatientContext
from .forms import addAppointmentForm
from .models import Doctor
from patientview.models import Patient
from dal import autocomplete
from django.db.models import Q

@login_required
@allowed_roles_redirect(['doctor'])
def home(request):
    context = {}
    patientcontext = makePatientContext(request)
    context['patientexample'] = patientcontext.patients()
    context['appointments'] = patientcontext.appointments()
    return render(request, 'drview/dr_home.html', context=context)

@login_required
def schedule(request):
    context = {}
    patientcontext = makePatientContext(request)
    doc = Doctor.objects.get(user_id=request.user.pk)
    if request.method == 'POST':
        form = addAppointmentForm(data=request.POST, user=doc)
        if form.is_valid():
            form.save()
            return redirect('drview:calendar')
    else:
        form = addAppointmentForm(user=doc)
    context['apptform'] = form
    context['patientexample'] = patientcontext.patients()
    context['appointments'] = patientcontext.appointments()

    return render(request, 'drview/calendar_view.html', context=context)

class patientAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Patient.objects.none()

        doc = Doctor.objects.get(user_id = self.request.user.pk)
        qs = doc.treats.all()
        if self.q:
            qs = qs.filter(Q(first_name__icontains=self.q)|Q(last_name__icontains=self.q))

        return qs

mysite/drview/templates/drview/snippets/calendar_script.html
{% block content %}
{% load mathfilters %}
{% autoescape off %}
<script>
      //Fix "a.receiveContext is not a function" error. MUST DO.

      document.addEventListener('DOMContentLoaded', function() {
        let calendarEl = document.getElementById('calendar');
        let draggableEl = document.getElementById('patientNav');

        let calendar = new FullCalendar.Calendar(calendarEl, {
          plugins: [ 'dayGrid', 'timeGrid', 'interaction', 'rrule'],
          defaultView: 'timeGridWeek',
          editable: true,
          droppable: true,
          height: 'parent',
          header: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
           },
           nowIndicator: true,
           selectable: true,
           dateClick: function(info){
            var view = calendar.view;
            if (view.type == 'dayGridMonth'){
                calendar.changeView('timeGridWeek');
                }
            if (view.type == 'timeGridWeek'){
                calendar.changeView('timeGridDay');
            }
            calendar.gotoDate(info.dateStr);
            calendar.select(info.dateStr);
           },
           /* -- This should totally work but it doesn't and I don't know why --
           dayRender: function(dayRenderInfo) {
            var element = dayRenderInfo.el;
            var view = dayRenderInfo.view;
            var date = dayRenderInfo.date;
            element.ondblclick = function(view, date) {
            if (view.type == 'dayGridMonth'){
                calendar.changeView('timeGridWeek');
                }
            if (view.type == 'timeGridWeek'){
                calendar.changeView('timeGridDay');
            }
            calendar.gotoDate(date.dateStr);
            calendar.select(date.dateStr);
           };
           },
           */
           events: [
           {% for appt in appointments %}
           {
            title: '{{appt.patient_name}}',
            {% if appt.rrule_str %}
            rrule: '{{appt.rrule_str}}',
            duration: '{{appt.time_end|sub:appt.time_start}}'
            {% else %}
            start: '{{appt.time_start|date:"Y-m-d H:i"}}',
            end: '{{appt.time_end|date:"Y-m-d H:i"}}'
            {% endif %}
           },
           {% endfor %}
           ],
        });
        calendar.render();
      });
</script>
{% endautoescape %}
{% endblock %}

mysite/drview/templates/drview/snippets/navbar.html
{% block content %}
{% load group_tags %}
<nav class="navbar-header navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Medsense</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'drview:homepage' %}">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'drview:calendar' %}">Calendar</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Dropdown
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="#">Action</a>
					<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Something else here</a>
				</div>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="#">Disabled</a>
			</li>
		</ul>
		<ul class="navbar-nav mr-right">
			<li>
				<form class="form-inline my-2 my-lg-0" style="padding-right: 15px">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  <i class="far fa-user-circle"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
					<a class="dropdown-item" href="#">{{user.get_username}}</a>
					<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
				</div>
			</li>
		</ul>
	</div>
</nav>
{% endblock %}

mysite/drview/templates/drview/snippets/patient_navbar.html
{% block content %}
    <div class="sidebar-container">
        <div class="sidebar-header">
                <nav id="patient-nav" class="navbar navbar-light bg-light navbar-fixed-top">
                <ul class="nav nav-pills" role="tablist">
                    <li>
                        <div class="nav-item btn-group">
                            <a class="btn nav-link" href="#appts">Appts</a>
                            <a class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#one">Today</a>
                                <a class="dropdown-item" href="#two">This Week</a>
                                <a class="dropdown-item" href="#three">This Month</a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#all-patients">All Patients</a>
                    </li>
                </ul>
                </nav>
        </div>
        <div id="patientNav" class="sidebar" data-spy="scroll" data-target="#patient-nav" data-offset="0">
            <nav>
            <h4 id="appts" class="scrollspy-head bg-light">Appointments</h4>
            <ul>
            {% for patient in appointments %}
                <li>
                    <div class="card" draggable="true" data-event='{ "title": "{{patient.patient_name}}", "duration": "01:00" }'>
                        <div class="card-header">
                            <a href="{% url 'testsite:test' %}" class="card-link">
                            {{patient.patient_name}}
                            </a>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{patient.time_start|date:"SHORT_DATETIME_FORMAT"}} at {{patient.location}}</p>
                            <p class="card-text">For: {{patient.reason}}</p>
                            <p class="card-text">Primary concern: {{patient.patient_concern}}</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
            </ul>
            <h4 id="all-patients" class="scrollspy-head bg-light">All Patients</h4>
            <ul>
            {% for patient in patientexample %}
                <li>
                    <div class="card" draggable="true" id="draggable-el" data-event='{ "title": "{{patient.patient_name}}", "duration": "01:00" }'>
                        <div class="card-header">
                            {{patient.patient_name}}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{patient.patient_concern}}</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </nav>
        </div>
    </div>
{% endblock %}