mysite/accounts/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views


app_name = 'accounts' #for namespacing of urls

urlpatterns = [path('', RedirectView.as_view(url = '/accounts/login/'), name = 'go-to-login'),
               path('signup/', views.register, name = 'Register'),
               path('login/', views.userLogin, name = 'login'),
               path('logout/', views.logout_view, name = 'logout')
               ]

mysite/drview/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView


app_name = 'drview' #for namespacing of urls

urlpatterns = [path('', RedirectView.as_view(url = '/dr-portal/home'), name = 'go-to-home'),
               path('home/', views.home, name = 'homepage'),
               path('calendar/', views.schedule, name = 'calendar'),
               path('patient-autocomplete/', views.patientAutoComplete.as_view(), name = 'patient-autocomplete')
               ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testsite/', include('testsite.urls')),
    path('', include('testsite.urls')),
    path('accounts/', include('accounts.urls')),
    path('dr-portal/', include('drview.urls')),
    path('patient-portal/', include('patientview.urls')),
]

mysite/patientview/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView


app_name = 'patientview' #for namespacing of urls

urlpatterns = [path('', RedirectView.as_view(url = '/patient-portal/home'), name = 'go-to-home'),
               path('home/', views.home, name = 'homepage'),
               ]

mysite/patientview/models.py
from django.db import models
from django.contrib.auth.models import User

class Concern(models.Model):

    concern = models.CharField(max_length=100)

    def __str__(self):
        return self.concern

class Patient(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=256)
    primary_concern = models.ForeignKey(Concern, on_delete=models.SET_NULL, blank=True, null=True, editable=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

mysite/patientview/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .decorators import allowed_roles_redirect

# Create your views here.
@login_required
@allowed_roles_redirect(['patient'])
def home(request):
    return render(request, 'patientview/patient_home.html')

mysite/patientview/templates/patientview/snippets/navbar.html
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="opacity: 0.7; height: 5%">
	<a class="navbar-brand" href="#">Medsense</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'patientview:homepage' %}">Home <span class="sr-only">(current)</span></a>
		  	</li>
		  	<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
		  	</li>
		  	<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  		Dropdown
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="#">Action</a>
			  		<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Something else here</a>
				</div>
		  	</li>
		  	<li class="nav-item">
				<a class="nav-link disabled" href="#">Disabled</a>
		  	</li>
		</ul>
		<ul class="navbar-nav mr-right">
			<li>
				<form class="form-inline my-2 my-lg-0" style="padding-right: 15px">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  <i class="far fa-user-circle"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
					<a class="dropdown-item" href="#">{{user.get_username}}</a>
					<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
				</div>
			</li>
	  </div>
</nav>
{% endblock %}