mysite/drview/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView


app_name = 'drview' #for namespacing of urls

urlpatterns = [path('', RedirectView.as_view(url = '/dr-portal/home'), name = 'go-to-home'),
               path('home/', views.home, name = 'homepage'),
               path('calendar/', views.schedule, name = 'calendar'),
               path('patient-autocomplete/', views.patientAutoComplete.as_view(), name = 'patient-autocomplete')
               ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testsite/', include('testsite.urls')),
    path('', include('testsite.urls')),
    path('accounts/', include('accounts.urls')),
    path('dr-portal/', include('drview.urls')),
    path('patient-portal/', include('patientview.urls')),
]

mysite/drview/models.py
from django.db import models
from django.contrib.auth.models import User
from patientview.models import Patient
from django.utils.translation import gettext as _

class Specialty(models.Model):

    specialty = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.specialty

class Doctor(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(max_length=256)
    specialties = models.ManyToManyField(Specialty,  blank=True, related_name='specialty_of')
    treats = models.ManyToManyField(Patient, blank=True, related_name='treated_by')
    appts = models.ManyToManyField(Patient, through='Appointments')

    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return ('{} {}'.format(self.first_name, self.last_name))

class Appointments(models.Model):
    #Choices for dropdown and repetition.
    NONE = ''
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'
    REPETITION_CHOICES = [
        (NONE, _('Repeat:')),
        (DAILY, _('Daily')),
        (WEEKLY, _('Weekly')),
        (MONTHLY, _('Monthly')),
    ]
    MONDAY = 'MO'
    TUESDAY = 'TU'
    WEDNESDAY = 'WE'
    THURSDAY = 'TH'
    FRIDAY = 'FR'
    WEEKDAY_CHOICES = [
        (MONDAY, _('Mon')),
        (TUESDAY, _('Tues')),
        (WEDNESDAY, _('Wed')),
        (THURSDAY, _('Thurs')),
        (FRIDAY, _('Fri')),
    ]

    #Model Fields
    starts_at = models.DateTimeField()
    ends_at = models.DateTimeField()
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    appt_location = models.CharField(max_length=100, null=True)
    appt_doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    appt_patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    reason = models.TextField(max_length=256, null=True)
    rrule = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return "{0} - {1}: {2} Appointment with {3}".format(self.starts_at, self.ends_at, self.appt_doctor,  self.appt_patient)

mysite/drview/forms.py
from django import forms
from .models import Appointments
from dal import autocomplete
from datetime import datetime
from django.utils.translation import gettext as _

class addAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(addAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['appt_patient'].queryset = self.user.treats.all()

    date = forms.DateField(label='Date',
                           widget=forms.DateInput(attrs={'class': 'datepicker form-control', 'placeholder': 'Date'}))
    starts_at = forms.TimeField(label='Start Time:', widget=forms.DateInput(
        attrs={'class': 'timepicker form-control', 'placeholder': 'Start Time'}))
    ends_at = forms.TimeField(label='End Time:', widget=forms.DateInput(
        attrs={'class': 'timepicker form-control', 'placeholder': 'End Time'}))
    appt_location = forms.CharField(label='Location', max_length=100,
                                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Location'}),
                                    required=False)
    reason = forms.CharField(label='Reason for Visit:', max_length=500,
                             widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Reason for Visit'}),
                             required=False)

    byweekday = forms.MultipleChoiceField(choices=Appointments.WEEKDAY_CHOICES,
                                          widget = forms.CheckboxSelectMultiple(attrs={'name':'weekday'}),
                                          required=False)

    frequency = forms.ChoiceField(widget=forms.Select({'class': 'form-control', 'data-target': 'weekdayCollapse'}),
                              choices=Appointments.REPETITION_CHOICES,
                              required=False)

    class Meta:
        model = Appointments
        fields = ('appt_patient', 'appt_location', 'reason',)
        widgets = {
            'appt_patient': autocomplete.ModelSelect2(url='drview:patient-autocomplete',
                                                      attrs={'class':'form-control',
                                                             'theme':'bootstrap',
                                                             'data-placeholder': 'Patient Name'})
        }

    # def is_valid(self):
    #     valid = super(addAppointmentForm, self).is_valid()
    #     self.cd = self.cleaned_data
    #     start_time = self.cd.get('starts_at')
    #     end_time = self.cd.get('ends_at')
    #
    #     if not valid:
    #         raise forms.ValidationError(_('Invalid form entry.'), code='invalid')
    #     elif start_time > end_time:
    #         raise forms.ValidationError(_('Start time must be before end time.'), code='Bad date order')
    #     else:
    #         return True

    def clean(self):
        self.cd = super(addAppointmentForm, self).clean()
        start_time = self.cd.get('starts_at')
        end_time = self.cd.get('ends_at')
        if start_time > end_time:
            raise forms.ValidationError(_('Start time must be before end time.'), code='Bad date order')
        return self.cd



    def save(self):

        start_datetime = datetime.combine(self.cd['date'], self.cd['starts_at'])
        end_datetime = datetime.combine(self.cd['date'], self.cd['ends_at'])
        weekdays = self.cd['byweekday']
        if self.cd['frequency']:
            frequency = r'DTSTART:{0};\nRRULE:FREQ={1};BYDAY={2}'.format(start_datetime.strftime('%Y%m%dT%H%M%S'), self.cd['frequency'], ','.join(map(str, weekdays)))
        else:
            frequency = ''

        self.instance.starts_at = start_datetime
        self.instance.ends_at = end_datetime
        self.instance.rrule = frequency
        self.instance.appt_doctor = self.user

        super(addAppointmentForm, self).save(commit=True)

mysite/drview/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .decorators import allowed_roles_redirect
from .static.drview.pyscripts.script_snippets import makePatientContext
from .forms import addAppointmentForm
from .models import Doctor
from patientview.models import Patient
from dal import autocomplete
from django.db.models import Q

@login_required
@allowed_roles_redirect(['doctor'])
def home(request):
    context = {}
    patientcontext = makePatientContext(request)
    context['patientexample'] = patientcontext.patients()
    context['appointments'] = patientcontext.appointments()
    return render(request, 'drview/dr_home.html', context=context)

@login_required
def schedule(request):
    context = {}
    patientcontext = makePatientContext(request)
    doc = Doctor.objects.get(user_id=request.user.pk)
    if request.method == 'POST':
        form = addAppointmentForm(data=request.POST, user=doc)
        if form.is_valid():
            form.save()
            return redirect('drview:calendar')
    else:
        form = addAppointmentForm(user=doc)
    context['apptform'] = form
    context['patientexample'] = patientcontext.patients()
    context['appointments'] = patientcontext.appointments()

    return render(request, 'drview/calendar_view.html', context=context)

class patientAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Patient.objects.none()

        doc = Doctor.objects.get(user_id = self.request.user.pk)
        qs = doc.treats.all()
        if self.q:
            qs = qs.filter(Q(first_name__icontains=self.q)|Q(last_name__icontains=self.q))

        return qs

mysite/drview/templates/drview/calendar_view.html
{% extends "drview/main.html" %}

{% block header %}
{% load static %}
<link rel="stylesheet" href="{% static 'fullcalendar/core/main.min.css' %}" />
<link rel="stylesheet" href="{% static 'fullcalendar/daygrid/main.min.css' %}" />
<link rel="stylesheet" href="{% static 'fullcalendar/timegrid/main.min.css' %}" />

<script src="{% static 'fullcalendar/core/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/timegrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/interaction/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/rrule/rrule.min.js' %}"></script>
<script src="{% static 'fullcalendar/rrule/main.min.js' %}"></script>
{% endblock %}

{% block content %}
<div class="row h-100" style="padding-top:50px">
    <div class="col-12 col-md-3 col-xl-2">
        {% include "drview/snippets/patient_navbar.html" %}
    </div>
    <div class="col-md-6 col-xl-8" style="height:99%">
        <div id="calendar"></div>
    </div>
    <div class="col-12 col-md-3 col-xl-2" style="padding-right:20px">
        <h2>Add Appointment</h2>
        <form method="POST">
            {% csrf_token %}
                <div class="form-group">
                    {{apptform.appt_patient}}
                </div>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker3'>
                        {{apptform.date}}
                        <div class="input-group-append">
                            <span class="input-group-text form-control"><i class="fas fa-calendar-alt"></i></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class='input-group' id='datetimepicker4'>
                        {{apptform.starts_at}}
                        {{apptform.ends_at}}
                        <div class="input-group-append">
                            <span class="input-group-text form-control"><i class="fas fa-clock"></i></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{apptform.appt_location}}
                </div>
                <div class="form-group">
                    {{apptform.reason.label}}
                    {{apptform.reason}}
                </div>
                <div class="form-group">
                    {{apptform.frequency}}
                </div>
                <div class="collapse" id="weekdayCollapse">
                    <div class="btn-group btn-group-toggle" data-toggle="buttons">
                        {% for checkbox in apptform.byweekday %}
                        <label class="btn btn-outline-secondary">
                            {{ checkbox.tag }}{{ checkbox.choice_label }}
                        </label>
                        {% endfor %}
                    </div>
                </div>
                <input class="btn btn-primary" type="submit" value="Add Appointment" style="margin-top:10px; margin-bottom:10px">
                <ul>
                {% if apptform.errors %}
                    {% for error in apptform.non_field_errors %}
                    <li>{{error}}</li>
                    {% endfor %}
                {% endif %}
                </ul>
        </form>
    </div>
</div>
{% endblock %}

{% block footer %}
    {{ apptform.media }}
    {% include "drview/snippets/calendar_script.html" %}
<script type="text/javascript">
    $(function () {
        /*
        $('.datepicker').datepicker({
            changeMonth: true,
            changeYear: true,
        }); */
        $("#id_frequency").change(function(){
            var selection = $("#id_frequency option:selected").text();
            if(selection == "Weekly"){
                    $("#weekdayCollapse").collapse("show");
                } else {
                    $("#weekdayCollapse").collapse("hide");
                }
        });
    });
</script>
{% endblock %}

mysite/drview/templates/drview/dr_home.html
{% extends "drview/main.html" %}

{% block content %}
<div class="row h-100">
    <div class="col-12 col-md-3 col-xl-2">
        {% include "drview/snippets/patient_navbar.html" %}
    </div>
</div>
{% endblock %}

mysite/drview/templates/drview/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'drview/css/style.css' %}">
    <script src="https://kit.fontawesome.com/9d9313ce4a.js" crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}

    {% if Title %}
        <title>{{Title}}</title>
    {% else %}
        <title>Your Medsense</title>
    {% endif %}
    {% include "drview/snippets/navbar.html" %}
</head>
<body>
    {% block content %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% block footer %}
{% endblock %}
</body>
</html>

mysite/drview/templates/drview/not_authorized.html
{% extends "drview/main.html" %}

{% block content %}
<p>You are not authorized to view this page</p>
{% endblock %}